name: teeth_align_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  chucker_flutter: ^1.6.1
  connectivity_plus: ^5.0.1
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.3
  flutter_gen: ^5.4.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_pin_code_fields: ^2.2.0
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.6.7
  http: ^1.1.0
  image: ^4.1.7
  image_picker: ^1.0.7
  injectable: ^2.3.2
  intl: any
  json_annotation: ^4.8.1
  mask_text_input_formatter: ^2.5.0
  package_info_plus: ^5.0.1
  pin_code_fields: ^8.0.1
  responsive_sizer: ^3.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  injectable_generator: ^2.4.2
  lint: ^2.1.2

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
